### ISSUE TITLE
Feature 1: User can view buttons corresponding to the sounds

### ISSUE THREAD

**Issue by Eugenepark215** [Eugenepark215/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view buttons correspinding to the sounds
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Clients can view buttons corresponding to the sounds within the database.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-11-07 at 11 01 05 AM](https://user-images.githubusercontent.com/97265272/200392855-0ee3d206-dd6a-4448-bd2c-e32235b6a513.png)
![Screen Shot 2022-11-07 at 11 01 23 AM](https://user-images.githubusercontent.com/97265272/200392863-afe8cc8a-6f20-48d7-b2b7-5b99728d4f1d.png)
![Screen Shot 2022-11-07 at 11 01 31 AM](https://user-images.githubusercontent.com/97265272/200392865-97831cb5-7d22-49d5-8343-f0267530acb6.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Create database with tables user, sounds, bookmarks
- [x] Bookmarks - userId, soundId
- [x] Users - userId, username, hashedPassword
- [x] Sounds - soundId, userId, fileUrl, uploadedAt
- [x] Upload sounds with mp3 files to sounds table

### ☁️ Server Tasks

- [x] Implement 'GET' request functionality
- [x] Make sure response is from the sounds table - fileUrl, soundName, soundId
- [x] Should be JSON array

### ⚡ Client Tasks

- [x] Retrieve infomation from database (sql)
- [x] Create a component that renders retrieved data as buttons from sounds table
- [x] Create function that assigns specific color to corresponding integer of soundId
- [x] Render name of button given the soundName
- [x] Apply CSS to match the wireframe

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
