### ISSUE TITLE
Feature 9: User can view oscillation of sound while recording

### ISSUE THREAD

**Issue by Eugenepark215** [Eugenepark215/final-project#10]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view audio visualizer while recording

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click the record icon and once it starts recording the audio visualizer will function

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="895" alt="Screen Shot 2022-11-18 at 11 56 32 AM" src="https://user-images.githubusercontent.com/97265272/202791792-ec4af71d-ebb9-4e48-a3fd-a6b9c3a3188e.png">
<img width="387" alt="Screen Shot 2022-11-18 at 11 56 14 AM" src="https://user-images.githubusercontent.com/97265272/202791797-45426b0c-2a24-43c3-ba33-51588264106e.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Update record component to include a function that will visualize audio
- [x] Render canvas element that will allow drawing: canvas.contextType('2d') will act as x,y cooridinate canvas
- [x] create new audiocontext that will be supplied into canvas visualization
- [x] using that audiocontext create a streamsource: 'audioCtx.createMediaStreamSource(stream)' and an analyser: 'audioCtx.createAnalyser()'
- [x] Set the fftSize of analyzer : fftSize must be power of 2 between 2^5 and 2^15 (A higher value will result in more details in the frequency domain but fewer details in the time domain.)
- [x] Create buffer variable of fftSize: analyser.frequencyBinCount (halfs the size of fft)
- [x] Create new Uint8Array by passing buffer variable
- [x] Pair the audiocontext source to analyzer
- [x] call and define a function that will 'draw' on the canvas
- [x] Set width of canvas
- [x] call requestAnimationFrame to animate on canvas
- [x] Use the Unit8Array within the analyser: analyser.getByteTimeDomainData(dataArray)
- [x] Style the canvas
- [x] Create for loop that will use the bufferlength and the the data within the Uint8Array to 'plot' the x,y  points within the canvas
### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
