### ISSUE TITLE
Feature 2: User can view single button detail

### ISSUE THREAD

**Issue by Eugenepark215** [Eugenepark215/final-project#12]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view single button detail page

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click the title of the button and view a page of the button detail

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="377" alt="Screen Shot 2022-11-09 at 12 04 13 PM" src="https://user-images.githubusercontent.com/97265272/200930263-95679f30-be01-41df-a194-951ab96d0451.png">
<img width="832" alt="Screen Shot 2022-11-09 at 12 03 52 PM" src="https://user-images.githubusercontent.com/97265272/200930267-c934edfb-9ee4-4c9a-9209-782c81ce149f.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to get single row of data corresponding to sound

### ⚡ Client Tasks

- [x] Implement hashroute to route to page component
- [x] Create a page component that renders single button view
- [x] Add new state property:current that will store information of the anchor-soundName
- [x] Utilize this.state.current to retrieve the corresponding row of data from sound 
- [x] Apply CSS to match wireframe

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
