### ISSUE TITLE
Feature 7: User can create an account

### ISSUE THREAD

**Issue by Eugenepark215** [Eugenepark215/final-project#13]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create an account or signup by inputting an unique username.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

If the user clicks the bookmark icon in the nav bar or the "Add to Bookmark" button in the button details a modal will appear prompting the user to sign up. 

## 🖼️ Wireframes
<img width="905" alt="Screen Shot 2022-11-15 at 2 05 04 PM" src="https://user-images.githubusercontent.com/97265272/202034950-af74722a-3151-422f-9d9d-d86a098fb1c8.png">
<img width="396" alt="Screen Shot 2022-11-15 at 2 04 41 PM" src="https://user-images.githubusercontent.com/97265272/202034956-41442ba6-cba2-4e56-a4cc-f13fbf4e7dd0.png">

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Make sure once the unique username and hashed password uploads to users

### ☁️ Server Tasks

- [x] Update `server/index.js` to create app.post for /api/users
- [x] Create function utilizing argon2 to hash password
- [x] Include hashed password into post request
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a sign-up modal component that will view depending on the state, which will be dictated by if the user clicked on the bookmark icon or the 'Add to Bookmark' button
- [x] Gather the input values
- [x] Create a fetch, post to /api/users and upload values

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
