### ISSUE TITLE
Feature 8 : User can login

### ISSUE THREAD

**Issue by Eugenepark215** [Eugenepark215/final-project#14]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can login

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

If user clicks on "Add to Bookmarks" or Bookmark icon modal will show asking the client to login
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
<img width="812" alt="Screen Shot 2022-11-16 at 2 34 16 PM" src="https://user-images.githubusercontent.com/97265272/202309183-0c8d3677-9210-4659-ab12-6cce577c6991.png">
<img width="839" alt="Screen Shot 2022-11-16 at 2 32 55 PM" src="https://user-images.githubusercontent.com/97265272/202309024-dbba520b-986c-404b-a15b-7135c043ef87.png">
<img width="835" alt="Screen Shot 2022-11-16 at 2 33 07 PM" src="https://user-images.githubusercontent.com/97265272/202309028-0944d053-cbf1-4cf7-84e0-d7e3de36135e.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Require jsonwebtoken
- [x] Update `server/index.js` to include new app.post api/users/sign-in 
- [x] Include sql code to recieve the userId and hashpassword data within user table
- [x] Get response of api/users/sign-up and verify to see if the req.body (login: username and password) matches
- [x] Throw error if it doesn't match
- [x] create payload variable and use jwt and process.env.TOKEN_SECRET to login
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client
- [x] Create authorization middleware to create access token variable, payload
- [x] Update error-middleware to include error for invalid login

### ⚡ Client Tasks

- [x] import jwtDecode
- [x] Create token and set value as window.localStorage.getItem('react-context-jwt')
- [x] When user is signing up use window.localStorage.setItem('react-context-jwt', token);
- [x] create fetch function that will be called when login req.body is submitted along with token in req.headers
- [x] If login req.body matches with the response use window.localStorage.setItem('react-context-jwt', token);
- [x] Update auth-form component to include anchor that switches to sign-in or sign-up

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
