### ISSUE TITLE
Bug 2: Certain audio is not playing on safari

### ISSUE THREAD

**Issue by Eugenepark215** [Eugenepark215/final-project#34]
#### Desired Behavior

> ##### The app should ...

Play audio from mobile and desktop

#### Actual Behavior

> ##### The app does this instead ...

Audio plays from recorded mobile plays on mobile but not desktop recorded

#### Steps to Reproduce

> ##### To trigger the bug, you must ...

Record and upload a sound from desktop

## ✅ Task List

> ##### Commit checklist for tasks needed to fix the bug.

- [x] Need to change the mimetype to one universal type
- **Clean Up**
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
