### ISSUE TITLE
Feature 3: User can record sounds

### ISSUE THREAD

**Issue by Eugenepark215** [Eugenepark215/final-project#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can record sounds

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click the record icon in the navbar which will route the user to the recording page.
User can click on a button and start recording.
User can click on the button to stop recording.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="620" alt="Screen Shot 2022-11-10 at 9 36 21 AM" src="https://user-images.githubusercontent.com/97265272/201166848-67530b6a-3552-4e20-9584-aad172e6cdc9.png">
<img width="802" alt="Screen Shot 2022-11-10 at 9 35 28 AM" src="https://user-images.githubusercontent.com/97265272/201166883-ff87882e-bd8d-4752-8e0f-19f191c55a9d.png">
<img width="787" alt="Screen Shot 2022-11-10 at 9 35 37 AM" src="https://user-images.githubusercontent.com/97265272/201166887-e78a7bd4-9714-42e8-a879-d8046396420a.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Create a page component for recording sounds
- [x] Change the button detail dependent on the status of the recording
- [x] Use navigator.mediaDevices.getUserMedia to access user microphone
- [x] make sure the constraint is for audio only
- [x] store blobs in array
- [x] create new Mediastream
- [x] set handleClicks for start and stop of recording and set property disable to true or false
- [x] create function that listens for 'stop' and assigns the blob an url 
- [x] render audio play back for recording

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
