### ISSUE TITLE
Feature 6: User can name recorded sound

### ISSUE THREAD

**Issue by Eugenepark215** [Eugenepark215/final-project#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can name their recordings

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can enter an entry of text in text form and name their recording.

## 🖼️ Wireframes
<img width="915" alt="Screen Shot 2022-11-15 at 10 49 02 AM" src="https://user-images.githubusercontent.com/97265272/202001321-0a0ced61-0848-4f3b-b344-ca31d6fc63e1.png">
<img width="369" alt="Screen Shot 2022-11-15 at 10 48 42 AM" src="https://user-images.githubusercontent.com/97265272/202001325-8b7eae0a-5cee-4077-a8a1-e301134ffecb.png">

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` app.post to receive the users req.body as a value
- [x] Update sql code to remove harded-coded name value
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update recording component to include text form input
- [x] Update fetch request to include req.body
- [x] Make sure the text form is only present when user is finished recording
- [x] Make sure that the new recording is present on home page

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
