### ISSUE TITLE
Feature 4: User can upload sounds

### ISSUE THREAD

**Issue by Eugenepark215** [Eugenepark215/final-project#8]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can upload their recordings to the server

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
Users can press a button and it will submit the sound to the server

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-11-11 at 10 03 56 AM](https://user-images.githubusercontent.com/97265272/201401614-44f2c06e-ce77-4a0c-ba4a-459e4beed9e5.png)
![Screen Shot 2022-11-11 at 10 03 03 AM](https://user-images.githubusercontent.com/97265272/201401618-9951bbe6-8c51-4f43-9d38-2d7b79dd7b04.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Confirm recording is within sound table

### ☁️ Server Tasks

- [x] Update `server/index.js` to include post request 'api/sound' reqbody
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Add to existing page component record to render submit button 
- [x] Add functionality that will convert blob to mp3 or audio file
- [x] Use same blob that is converted to url 
- [x] Add functionality to submit button that will send audio file to server
- [x] Once the sound is submitted the button should be listed first on home
- [x] Reverse the array within this.state.sound before map()

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
