### ISSUE TITLE
Feature 10 : User can view bookmarks

### ISSUE THREAD

**Issue by Eugenepark215** [Eugenepark215/final-project#9]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view the bookmark page component
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
User can click the bookmark icon or the add to bookmark button and will be routed to the bookmark component

User can click the bookmark icon to view the bookmark page

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
<img width="380" alt="Screen Shot 2022-11-18 at 2 21 51 PM" src="https://user-images.githubusercontent.com/97265272/202812938-24275f52-afaf-4250-80c5-543a149eb50f.png">
<img width="862" alt="Screen Shot 2022-11-18 at 2 22 19 PM" src="https://user-images.githubusercontent.com/97265272/202812939-768c4938-42fb-4313-953b-1926e3849c07.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `data.sql` to include test data values

### ☁️ Server Tasks

- [x] Update `server/index.js` to include an app.get api/bookmark
- [x] Return value should be soundid where userid = this.context.user.userId
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Implement hashroute to route to bookmark component
- [x] Include functionality for the bookmark icon that will route to bookmark page component
- [x] Create a page component that renders the bookmark
- [x] Create fetch request to get soundid from where userid = this.context.user.userId
- [x] Apply css to match wireframe

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
